sudo: required
services:
  - docker

before_install:
  - docker build -t dennisjs/personalsite -f client/Dockerfile.dev client/

script:
  - docker run -e CI=true dennisjs/personalsite npm run ci_test -- --coverage