sudo: required
services:
  - docker

before_install:
  - docker build -t dennisjs/personalsite -f client/Dockerfile.dev client/

script:
  - docker run dennisjs/personalsite npm run ci_test -- --coverage

# deploy:
#   provider: elasticbeanstalk
#   region: "TODO:us-west-2"
#   app: "SAME AS elastic bean stalk name ex:personalSite"
#   env: "TODO:Docker-env"
#   bucket_name: "todo:search s3 and find appropriate bucket"
#   bucket_path: "todo:same as app name"
#   on:
#     branch: master

