sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project k8s-blog-244007
  - gcloud config set compute/zone us-west1-b
  - gcloud container clusters get-credentials blog-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t dennisjs/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dennisjs/client-test npm run ci_test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master