version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '4000:80'

  mysql-db:
    image: 'mysql:8.0.16'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpassword
      MYSQL_DATABASE: personal_blog
      MYSQL_USER: user

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app

  # migration:
  #   image: api
  #   command: ["./wait-for-it/wait-for-it.sh", "mysql:3306", "--", "npm", "run", "migrate"]
  #   links:
  #     - mysql
  #   depends_on:
  #     - mysql

  # tests:
  #   build:
  #     context: client
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #       - /app/node_modules
  #       - ./client:/app
  #   command: ["npm", "run", "test"]