version: '3'
services:
  web:
    build:
      context: client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/client/node_modules
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
  tests:
    build:
      context: client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/client/node_modules
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    command: ["npm", "run", "test"]