version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '4000:80'
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: dennisjs
      POSTGRES_DB: personal_blog
    ports:
      - '5432:5432'

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
      - db
    environment:
      DB_HOST: 'db'
      DB_PORT: '5432'
      DB_USER: 'dennisjs'
      DB_PASSWORD: 'password'
      DB_DATABASE: 'personal_blog'
      WAIT_HOSTS: 'db:5432'

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app

  # migration:
  #   image: api
  #   command: ["./wait-for-it/wait-for-it.sh", "mysql:3306", "--", "npm", "run", "migrate"]
  #   links:
  #     - mysql
  #   depends_on:
  #     - mysql

  # mysql-db:
  #   image: 'mysql:8.0.16'
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: mysqlrootpassword
  #     MYSQL_DATABASE: personal_blog
  #     MYSQL_USER: user

  # tests:
  #   build:
  #     context: client
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #       - /app/node_modules
  #       - ./client:/app
  #   command: ["npm", "run", "test"]