version: '3'
services:
  mysql:
    image: 'mysql:8.0.16'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
  # web:
  #   build:
  #     context: client
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - /app/client/node_modules
  #     - ./client/src:/app/client/src
  #     - ./client/public:/app/client/public
  # tests:
  #   build:
  #     context: client
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /app/client/node_modules
  #     - ./client/src:/app/client/src
  #     - ./client/public:/app/client/public
  #   command: ["npm", "run", "test"]