version: '3'
services:
  mysql:
    image: 'mysql:8.0.16'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    # ports:
    #   - '3306:3306'
    # expose:
    #   - '3306'
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  # tests:
  #   build:
  #     context: client
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #       - /app/node_modules
  #       - ./client:/app
  #   command: ["npm", "run", "test"]