FROM node:8.16.0-alpine

WORKDIR '/app'
RUN npm install knex -g

COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm install
COPY . .

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

# CMD ["npm", "run", "server-dev"]
CMD /wait && npm run migrate && npm run server-dev