export const BLOG_ACTION = {
  POST_IMAGE: "POST_IMAGE",
  CREATE_BLOG_REQUEST: "CREATE_BLOG_REQUEST",
  CREATE_BLOG_SUCCESS: "CREATE_BLOG_SUCCESS",
  CREATE_BLOG_FAILURE: "CREATE_BLOG_FAILURE",

  FETCH_BLOG_SUCCESS: "FETCH_BLOG_SUCCESS",
  FETCH_BLOG_FAILURE: "FETCH_BLOG_FAILURE",
};