export const BLOG_ACTION = {
  POST_IMAGE: "POST_IMAGE",
  CREATE_BLOG_REQUEST: "CREATE_BLOG_REQUEST",
  CREATE_BLOG_SUCCESS: "CREATE_BLOG_SUCCESS",
  CREATE_BLOG_FAILURE: "CREATE_BLOG_FAILURE",

  FETCH_BLOG_SUCCESS: "FETCH_BLOG_SUCCESS",
  FETCH_BLOG_FAILURE: "FETCH_BLOG_FAILURE",
};

export const AUTH_ACTION = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const USER_ACTION = {
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
}